### ISSUE TITLE
4X4 grid

### ISSUE THREAD

**Issue by AnshKGoyal** [DedInc/byerecaptcha#10]
"if pieces == 16:
            clickReloadButton()"
here is it possible to solve for 4X4 grid too instead of reloading it, i mean will you add it in future releases?
thanks for checking out my question

**Comment by DedInc** [comment]
The model is trained for 3x3 mesh images, theoretically it is possible to reduce 4x4 to a size that and 3x3 but I think the quality will be lost and it will not be practical
