### ISSUE TITLE
Error when trying to solve recaptcha v2

### ISSUE THREAD

**Issue by RichardAtCT** [DedInc/byerecaptcha#2]
Hey! Not sure if I am doing something wrong, but I am getting the following error when trying to use the solveRecaptcha() function. Any guesses? :)

` File "/Users/.../site-packages/byerecaptcha/byerecaptcha.py", line 370, in solveRecaptcha
    getFrames(invisible)
  File "/Users/.../site-packages/byerecaptcha/byerecaptcha.py", line 81, in getFrames
    CheckBox = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "recaptcha-anchor")))
  File "/Users/.../site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)`

**Comment by DedInc** [comment]
You need to use solveRecaptcha(driver), where driver - selenium driver!

Also, on some websites element recaptcha-anchor doesn't exists and byerecaptcha can't find it :)
